// <auto-generated />
using System;
using BPGezinswetenschappen.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BPGezinswetenschappen.DAL.Migrations
{
    [DbContext(typeof(BPContext))]
    [Migration("20250517191631_seeRolesUserSlotsPresentationSlots")]
    partial class seeRolesUserSlotsPresentationSlots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.Organisation", b =>
                {
                    b.Property<int>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganisationId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganisationId");

                    b.ToTable("Organisations", (string)null);
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<bool?>("Approved")
                        .HasColumnType("bit");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("int");

                    b.Property<bool?>("Reviewed")
                        .HasColumnType("bit");

                    b.Property<string>("Stage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<bool?>("Supported")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ProjectId");

                    b.HasIndex("CoachId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("StudentId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.Proposal", b =>
                {
                    b.Property<int>("ProposalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProposalId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProposalId");

                    b.ToTable("Proposals", (string)null);
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Application")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Expertise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Sub")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Classroom", b =>
                {
                    b.Property<int>("ClassroomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassroomId"));

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClassroomId");

                    b.ToTable("Classroom", (string)null);
                });

            modelBuilder.Entity("DAL.Models.ExamPeriod", b =>
                {
                    b.Property<int>("ExamPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamPeriodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearId")
                        .HasColumnType("int");

                    b.HasKey("ExamPeriodId");

                    b.HasIndex("YearId");

                    b.ToTable("ExamPeriods", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Presentation", b =>
                {
                    b.Property<int>("PresentationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PresentationId"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("PresentationId");

                    b.HasIndex("CoachId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("StudentId");

                    b.ToTable("Presentations", (string)null);
                });

            modelBuilder.Entity("DAL.Models.PresentationDay", b =>
                {
                    b.Property<int>("PresentationDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PresentationDayId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExamPeriodId")
                        .HasColumnType("int");

                    b.HasKey("PresentationDayId");

                    b.HasIndex("ExamPeriodId");

                    b.ToTable("PresentationDays", (string)null);
                });

            modelBuilder.Entity("DAL.Models.PresentationSlot", b =>
                {
                    b.Property<int>("PresentationId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.HasKey("PresentationId", "SlotId");

                    b.HasIndex("SlotId");

                    b.ToTable("PresentationSlots", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Slot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("PresentationDayId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("PresentationDayId");

                    b.ToTable("Slots", (string)null);
                });

            modelBuilder.Entity("DAL.Models.UserSlot", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SlotId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SlotId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SlotId");

                    b.ToTable("UserSlots", (string)null);
                });

            modelBuilder.Entity("DAL.Models.Year", b =>
                {
                    b.Property<int>("YearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YearId"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YearId");

                    b.ToTable("Years", (string)null);
                });

            modelBuilder.Entity("ProjectTopic", b =>
                {
                    b.Property<int>("ProjectsProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TopicsTopicId")
                        .HasColumnType("int");

                    b.HasKey("ProjectsProjectId", "TopicsTopicId");

                    b.HasIndex("TopicsTopicId");

                    b.ToTable("ProjectTopic");
                });

            modelBuilder.Entity("ProposalTopic", b =>
                {
                    b.Property<int>("ProposalsProposalId")
                        .HasColumnType("int");

                    b.Property<int>("TopicsTopicId")
                        .HasColumnType("int");

                    b.HasKey("ProposalsProposalId", "TopicsTopicId");

                    b.HasIndex("TopicsTopicId");

                    b.ToTable("ProposalTopic");
                });

            modelBuilder.Entity("TopicUser", b =>
                {
                    b.Property<int>("TopicsTopicId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("TopicsTopicId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("TopicUser");
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.Project", b =>
                {
                    b.HasOne("BPGezinswetenschappen.DAL.Models.User", "Coach")
                        .WithMany("CoachProjects")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BPGezinswetenschappen.DAL.Models.Organisation", "Organisation")
                        .WithMany("Projects")
                        .HasForeignKey("OrganisationId");

                    b.HasOne("BPGezinswetenschappen.DAL.Models.Proposal", "Proposal")
                        .WithMany("Projects")
                        .HasForeignKey("ProposalId");

                    b.HasOne("BPGezinswetenschappen.DAL.Models.User", "Student")
                        .WithMany("StudentProjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Coach");

                    b.Navigation("Organisation");

                    b.Navigation("Proposal");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.ExamPeriod", b =>
                {
                    b.HasOne("DAL.Models.Year", "Year")
                        .WithMany("ExamPeriods")
                        .HasForeignKey("YearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Year");
                });

            modelBuilder.Entity("DAL.Models.Presentation", b =>
                {
                    b.HasOne("BPGezinswetenschappen.DAL.Models.User", "Coach")
                        .WithMany("CoachPresentations")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BPGezinswetenschappen.DAL.Models.User", "Expert")
                        .WithMany("ExpertPresentations")
                        .HasForeignKey("ExpertId");

                    b.HasOne("BPGezinswetenschappen.DAL.Models.User", "Student")
                        .WithMany("StudentPresentations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Coach");

                    b.Navigation("Expert");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DAL.Models.PresentationDay", b =>
                {
                    b.HasOne("DAL.Models.ExamPeriod", "ExamPeriod")
                        .WithMany("PresentationDays")
                        .HasForeignKey("ExamPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamPeriod");
                });

            modelBuilder.Entity("DAL.Models.PresentationSlot", b =>
                {
                    b.HasOne("DAL.Models.Presentation", "Presentation")
                        .WithMany("Slots")
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Slot", "Slot")
                        .WithMany("Presentations")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentation");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("DAL.Models.Slot", b =>
                {
                    b.HasOne("DAL.Models.Classroom", "Classroom")
                        .WithMany("Slots")
                        .HasForeignKey("ClassroomId");

                    b.HasOne("DAL.Models.PresentationDay", "PresentationDay")
                        .WithMany("Slots")
                        .HasForeignKey("PresentationDayId");

                    b.Navigation("Classroom");

                    b.Navigation("PresentationDay");
                });

            modelBuilder.Entity("DAL.Models.UserSlot", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("UserSlots")
                        .HasForeignKey("RoleId");

                    b.HasOne("DAL.Models.Slot", "Slot")
                        .WithMany("Availabilities")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BPGezinswetenschappen.DAL.Models.User", "User")
                        .WithMany("AvailableSlots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Slot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTopic", b =>
                {
                    b.HasOne("BPGezinswetenschappen.DAL.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BPGezinswetenschappen.DAL.Models.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProposalTopic", b =>
                {
                    b.HasOne("BPGezinswetenschappen.DAL.Models.Proposal", null)
                        .WithMany()
                        .HasForeignKey("ProposalsProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BPGezinswetenschappen.DAL.Models.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TopicUser", b =>
                {
                    b.HasOne("BPGezinswetenschappen.DAL.Models.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BPGezinswetenschappen.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.Organisation", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.Proposal", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("BPGezinswetenschappen.DAL.Models.User", b =>
                {
                    b.Navigation("AvailableSlots");

                    b.Navigation("CoachPresentations");

                    b.Navigation("CoachProjects");

                    b.Navigation("ExpertPresentations");

                    b.Navigation("StudentPresentations");

                    b.Navigation("StudentProjects");
                });

            modelBuilder.Entity("DAL.Models.Classroom", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DAL.Models.ExamPeriod", b =>
                {
                    b.Navigation("PresentationDays");
                });

            modelBuilder.Entity("DAL.Models.Presentation", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DAL.Models.PresentationDay", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("UserSlots");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.Slot", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Presentations");
                });

            modelBuilder.Entity("DAL.Models.Year", b =>
                {
                    b.Navigation("ExamPeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
